usuario/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('cadastro', views.cadastro, name='cadastro'),
    path('login', views.login, name='login'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('logout', views.logout, name='logout'),
    path('lista', views.lista, name='lista'),
    path('editar/<str:username>', views.editar, name='editar'),
    path('deletar_usuario/<int:user_id>', views.deletar_usuario, name='deletar_usuario'),
    path('administrativo/editar_usuario', views.editar_usuario, name='editar_usuario'),
    path('administrativo/alterar_senha', views.alterar_senha, name='alterar_senha'),
    path('administrativo', views.administrativo, name='administrativo'),
    #alterar senha
    path('recuperar_senha', auth_views.PasswordResetView.as_view(template_name="usuarios/recuperar_senha.html"), name="reset_password"),
    path('nova_senha_enviada', auth_views.PasswordResetDoneView.as_view(template_name="usuarios/email_enviado.html"), name="password_reset_done"),
    path('senha/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="usuarios/nova_senha.html"), name="password_reset_confirm"),
    path('senha_recuperada', auth_views.PasswordResetCompleteView.as_view(template_name="usuarios/senha_alterada.html"), name="password_reset_complete"),
]

usuario/models.py
from django.db import models

# Create your models here.

usuario/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserChangeForm

from usuario.validation import verifica_email, verifica_senha, email_existe


class Login(forms.Form):
    email = forms.EmailField(label='Email: ', max_length=200, widget=forms.EmailInput(
        attrs={
            'class': 'form-control',
            'maxlength': '200',
            'placeholder': "Entre com o email cadastrado",
            'name': 'email'
        }
    ))

    senha = forms.CharField(label='Senha: ', widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': "Digite aqui sua senha",
            'name': 'senha1'
        }
    ))

    def clean(self):
        email = self.cleaned_data.get('email')

        lista_erros = {}

        email_existe(email, lista_erros)

        if lista_erros is not None:
            for erro in lista_erros:
                mensagem_erro = lista_erros[erro]
                self.add_error(erro, mensagem_erro)
        return self.cleaned_data


class UserCreationForm(forms.Form):
    first_name = forms.CharField(label='Nome', max_length=20, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'maxlength': '200',
            'placeholder': "Ex.: José",
            'name': 'nome'
        }
    ))

    last_name = forms.CharField(label='Sobrenome', max_length=150, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'maxlength': '200',
            'placeholder': "Ex.: da Silva",
            'name': 'sobrenome'
        }
    ))

    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)

    email = forms.EmailField(label='Email', max_length=200, widget=forms.EmailInput(
        attrs={
            'class': 'form-control',
            'maxlength': '200',
            'placeholder': "Ex.: jose@unemat.br",
            'name': 'email'
        }
    ))

    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': "Digite sua senha",
            'name': 'senha1'
        }
    ))

    password2 = forms.CharField(label='Confirmação', widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': "Confirme sua senha",
            'name': 'senha2'
        }
    ))

    def clean(self):
        email = self.cleaned_data.get('email')
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        lista_erros = {}

        verifica_email(email, lista_erros)
        verifica_senha(password1, password2, lista_erros)

        if lista_erros is not None:
            for erro in lista_erros:
                mensagem_erro = lista_erros[erro]
                self.add_error(erro, mensagem_erro)
        return self.cleaned_data

    def save(self, commit=True):
        user = User.objects.create_user(
            is_staff=True,
            username=self.cleaned_data['username'],
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password1']
        )
        return user


class EditarUsuarioForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',

        )

    first_name = forms.CharField(label='Nome: ', max_length=20, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'maxlength': '200',
            'placeholder': "Ex.: José",
            'name': 'nome'
        }
    ))

    last_name = forms.CharField(label='Sobrenome: ', max_length=150, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'maxlength': '200',
            'placeholder': "Ex.: da Silva",
            'name': 'sobrenome'
        }
    ))

    email = forms.EmailField(label='E-mail: ', max_length=200, widget=forms.EmailInput(
        attrs={
            'class': 'form-control',
            'maxlength': '200',
            'placeholder': "Ex.: jose@unemat.br",
            'name': 'email'
        }
    ))


class FormErro(forms.Form):

    email = forms.EmailField()

    def clean(self):
        lista_erros = {}

        if lista_erros is not None:
            for erro in lista_erros:
                mensagem_erro = lista_erros[erro]
                self.add_error(erro, mensagem_erro)
        return self.cleaned_data

usuario/views.py
from django.contrib.auth import update_session_auth_hash
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import auth
import datetime
from coordenador_curso.models import Projeto, Bolsistas
from professores.forms import EditaProf
from professores.models import Professores
from usuario.forms import UserCreationForm, EditarUsuarioForm, FormErro, Login
from django.contrib.auth.forms import PasswordChangeForm


def cadastro(request):
    if request.method == 'GET':

        user = UserCreationForm()
        context = {
            'new_user': user
        }
        return render(request, 'usuarios/cadastro.html', context)

    elif request.method == 'POST':

        user = UserCreationForm(request.POST)
        str_nome = request.POST.get('first_name')
        str_sobrenome = request.POST.get('last_name')

        nome = ''.join(str_nome.split())
        sobrenome = ''.join(str_sobrenome.split())

        str_user = nome + sobrenome

        user_size = len(str_user)

        if user_size > 10:
            user_name = ''
            for i in range(0, 9):
                user_name += str_user[i].lower()
        else:
            user_name = str_user

        if User.objects.filter(username=user_name).exists():
            user_name = user_name[:-1]
            new = 1
            user_name += str(new)
            while User.objects.filter(username=user_name).exists():
                if User.objects.filter(username=user_name).exists():
                    user_name = user_name[:-1]
                    new += 1
                    user_name += str(new)
                else:
                    user_name += str(new)
                    break

        request.POST._mutable = True
        request.POST['username'] = user_name
        request.POST._mutable = False

        if user.is_valid():
            user.is_staff = True
            user.save()
            return redirect('lista')
        else:
            context = {
                'new_user': user
            }
            return render(request, 'usuarios/cadastro.html', context)


def editar(request, username):
    if request.method == 'GET':
        usuario = User.objects.get(username=username)
        form = EditarUsuarioForm(instance=usuario)
        context = {
            'form': form,
            'user': usuario,
        }
        return render(request, 'usuarios/editar.html', context)

    if request.method == 'POST':
        usuario = User.objects.get(username=username)
        form = EditarUsuarioForm(request.POST, instance=usuario)

        email_user = usuario.email
        email = request.POST.get('email')

        if email_user != email:
            if User.objects.filter(email=email).exists():
                form.add_error('email', 'Email já cadastrado!')

        if form.is_valid():
            form.save()
            return redirect('lista')
        else:
            context = {
                'form': form,
            }
            return render(request, 'usuarios/editar.html', context)


def login(request):
    if request.method == 'GET':
        form = Login()
        context = {
            'form': form
        }
        return render(request, 'usuarios/login.html', context)
    if request.method == 'POST':
        form = Login(request.POST)
        email = request.POST.get('email')
        senha = request.POST.get('senha')

        if User.objects.filter(email=email):
            user = User.objects.filter(email=email).get()
            valido = user.check_password(senha)
            if not valido:
                form.add_error('senha', 'Senha incorreta!')

        if form.is_valid():
            if User.objects.filter(email=email).exists():
                nome = User.objects.filter(email=email).values_list('username', flat=True).get()
                user = auth.authenticate(request, username=nome, password=senha)
                if user is not None:
                    auth.login(request, user)
                    return redirect('dashboard')
        context = {
            'form': form
        }
        return render(request, 'usuarios/login.html', context)


def logout(request):
    auth.logout(request)
    return redirect('login')


def dashboard(request):
    if request.user.is_authenticated:

        projetos = Projeto.objects.order_by('id')

        hoje = datetime.datetime.now().date()
        delta = datetime.timedelta(days=90)
        prox_mes = hoje+delta

        projetos = projetos.filter(data_de_fim__gte=hoje, data_de_fim__lte=prox_mes).order_by('data_de_fim')

        context = {
            'projetos': projetos
        }

        return render(request, 'usuarios/dashboard.html', context)
    else:
        return redirect('index')


def deletar_usuario(request, user_id):
    usuario = User.objects.get(id=user_id)
    usuario.delete()
    return redirect('lista')


def lista(request):
    usuarios = User.objects.order_by('id').filter(is_superuser=False)
    for usuario in usuarios:
        existe = Bolsistas.objects.filter(email=usuario.email).exists()
        if existe:
            usuarios = usuarios.exclude(email=usuario.email)
    page = request.GET.get('page', 1)
    paginator = Paginator(usuarios, 10)

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    context = {'usuarios': users}

    return render(request, 'usuarios/lista.html', context)


def alterar_senha(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('logout')
        else:
            context = {
                'form': form
            }
            return render(request, 'usuarios/password_change_form.html', context)

    else:
        form = PasswordChangeForm(user=request.user)
        context = {
            'form': form
        }
        return render(request, 'usuarios/password_change_form.html', context)


def editar_usuario(request):
    if request.method == 'POST':
        form = EditarUsuarioForm(request.POST, instance=request.user)

        email_user = request.user.email
        email = request.POST.get('email')

        if email_user != email:
            if User.objects.filter(email=email).exists():
                erro = FormErro(request.POST)
                request.POST._mutable = True
                request.POST['email'] = email
                request.POST._mutable = False
                erro.add_error('email', 'Email já cadastrado!')
                form.add_error('email', 'Já cadastrado')

        if request.user.is_superuser:
            professor = Professores.objects.get(email=request.user.email)
            form_prof = EditaProf(request.POST, instance=professor)

            str_nome = request.POST.get('first_name')
            str_sobrenome = request.POST.get('last_name')
            email = request.POST.get('email')
            nome_completo = str_nome + ' ' + str_sobrenome

            request.POST._mutable = True
            request.POST['nome_professor'] = str_nome
            request.POST['sobrenome_professor'] = str_sobrenome
            request.POST['email'] = email
            request.POST['nome_completo'] = nome_completo
            request.POST._mutable = False

            if email_user != email:
                if User.objects.filter(email=email).exists():
                    erro = FormErro(request.POST)
                    request.POST._mutable = True
                    request.POST['email'] = email
                    request.POST._mutable = False
                    erro.add_error('email', 'Email já cadastrado!')
                    form.add_error('email', 'Já cadastrado')
            else:
                form_prof.save()

        if form.is_valid():
            form.save()
            context = {
                'form': form,
            }
            return render(request, 'usuarios/administrativo/editado.html', context)

        else:
            form = EditarUsuarioForm(instance=request.user)
            context = {
                'form': form,
                'erro': erro,
            }
            return render(request, 'usuarios/administrativo/editar_usuario.html', context)

    else:
        form = EditarUsuarioForm(instance=request.user)
        context = {'form': form}
        return render(request, 'usuarios/administrativo/editar_usuario.html', context)


def administrativo(request):
    return render(request, 'usuarios/administrativo.html')

templates/usuarios/administrativo.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'partials/_header.html' %}

{% include 'partials/_adm.html' %}

<div class="container">
    {{ form }}
</div>

{% include 'partials/_footer.html' %}

{% endblock %}

templates/usuarios/cadastro.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'partials/_header.html' %}

<style>

.btn-green{
background-color:#008000
;color: #FFF;
}

.btn-green:hover{
color:#fff;
background-color: #009900;
border-color: #008000;
}

</style>

<main role="main">
    <div class="container">
        <div class="contact-area">
            <div class="container mt-4">
                <div class="row">
                    <div class="col-12">
                        <div class="section-heading">
                            <h2>Criar conta</h2>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="contact-form-area">
                            <form action="{% url 'cadastro' %}" method="POST">

                                <div class="row">
                                    <div class="col-12 col-lg-6">
                                        {{new_user.first_name.label_tag}}
                                        {{new_user.first_name}}
                                    </div>
                                    <div class="col-12 col-lg-6">
                                        {{new_user.last_name.label_tag}}
                                        {{new_user.last_name}}
                                    </div>
                                    <div class="col-12 col-lg-12">
                                        {{new_user.email.label_tag}}
                                        {{new_user.email}}
                                    </div>

                                    {% for error in new_user.email.errors %}
                                    <section class="alert alert-danger col-12" role="alert">
                                        {{ new_user.email.errors }}
                                    </section>
                                    {% endfor %}

                                    <div class="col-12 col-lg-6">
                                        {{new_user.password1.label_tag}}
                                        {{new_user.password1}}
                                    </div>
                                    <div class="col-12 col-lg-6">
                                        {{new_user.password2.label_tag}}
                                        {{new_user.password2}}
                                    </div>
                                    {% for error in new_user.password1.errors %}
                                    <section class="alert alert-danger col-12" role="alert">
                                        {{ new_user.password1.errors }}
                                    </section>
                                    {% endfor %}

                                </div>
                                <div class="d-flex p-2 bd-highlight">
                                    <div class="col-12 text-center">
                                        <button class="btn btn-green" type="submit">Criar sua conta</button>
                                        {% csrf_token %}
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% include 'partials/_footer.html' %}

{% endblock %}

templates/usuarios/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'partials/_header.html' %}

<!-- Begin page content -->
<main role="main" class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Projetos UNEMAT</h1>
      <h3>Todos os projetos de extensão da UNEMAT serão publicados aqui!</h3>
      <h3>Clique em projetos para ver todos ou pesquise algum projeto especifico</h3>
  </div>
</main>

<div class="contact-area section-padding-0-80">
   <div class="container">
       <div class="row">
           <div class="col-12">
               <div class="section-heading">
                   <br>
                   <h3>Olá {{ user.first_name.capitalize }}!</h3>
               </div>
           </div>
       </div>
   </div>
</div>
<br><br>
{% if projetos %}
    <div class="container">
    <h3>Os seguintes projetos estão para vencer em 90 dias!</h3>
        <div class="table-responsive">
          <table class="table">
            <thead>
                <tr>
                    <th style="width: 30%" scope="col">Projeto</th>
                    <th style="width: 40%" scope="col">Coordenador</th>
                    <th class="font-weight-bold text-danger" style="width: 30%" scope="col">Data de Termino</th>
                </tr>
            </thead>
            <tbody>
                {% for projeto in projetos %}
                <tr>
                    <td><a href="{% url 'projeto' projeto.id %}">{{ projeto.nome_projeto }}</a></td>
                    <td>{{ projeto.coordenador_projeto }}</td>
                    <td class="font-weight-bold text-danger">{{ projeto.data_de_fim }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
    {% endif %}

{% include 'partials/_footer.html' %}

{% endblock %}

templates/usuarios/editar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'partials/_header.html' %}


<style>
a:link, a:visited{
  color: #006600;
}

.btn-green{
background-color:#008000
;color: #FFF;
}

.btn-green:hover{
color:#fff;
background-color: #009900;
border-color: #008000;
}

</style>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

<!-- Begin page content -->

<main role="main">
    <div class="container mt-4">
        <form action="" class="form-group" method="POST">{% csrf_token %}

            <div class="form-group">
                {{form.first_name.label_tag}}
                {{form.first_name}}
            </div>

            <div class="form-group">
                {{form.last_name.label_tag}}
                {{form.last_name}}
            </div>

            <div class="form-group">
                {{ form.email.label_tag }}
                {{ form.email }}
            </div>
            {% for error in form.email.errors %}
            <section class="alert alert-danger col-12 col-lg-12 " role="alert">
                {{ form.email.errors }}
            </section>
            {% endfor %}

            <div class="form-group">
                <input type="hidden" class="form-control" name="username" value="{{form.username}}" maxlength="254" id="id_username">
            </div>


            <br>
            <div class="submit-row">
                <button type="submit" class="btn btn-green" name="_save">Salvar</button>
            </div>

        </form>
    </div>
</main>

{% include 'partials/_footer.html' %}

{% endblock %}

templates/usuarios/email_enviado.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'partials/_header.html' %}

<style>

.btn-green{
background-color:#008000
;color: #FFF;
}

.btn-green:hover{
color:#fff;
background-color: #009900;
border-color: #008000;
}

.btn-xl {
    width: 20%;
}

</style>

<main role="main">
    <div class="container">
<!-- ##### Contact Form Area Start ##### -->
        <div class="contact-area section-padding-0-80">
            <div class="container mt-4">
                <div class="row">
                    <div class="col-12">
                        <div class="section-heading">
                            <h2>Redefinição de senha enviada!</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="contact-form-area">
                            <p>Nós te enviamos um email com instruções para configurar sua senha, se uma conta existe com o email fornecido. Você receberá a mensagem em breve.</p>
                            <p>Se você não recebeu um email, por favor certifique-se que você forneceu o endereço que você está cadastrado, e verifique sua pasta de spam.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<script>
function exibirCriarConta()
{
     location.href = "{% url 'cadastro' %}";
}
</script>

{% include 'partials/_footer.html' %}

{% endblock %}

templates/usuarios/lista.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'partials/_header.html' %}

<style>
a:link, a:visited{
  color: #006600;
}

.btn-large {
    padding: 5px 15px;
    font-size: 15px;
}

table {
  /* Set "my-sec-counter" to 0 */
  counter-reset: my-sec-counter;
}

p::before {
  /* Increment "my-sec-counter" by 1 */
  counter-increment: my-sec-counter;
  content: counter(my-sec-counter) ". ";
  font-size:18px;
}

</style>


<!-- Begin page content -->
<main role="main" class="flex-shrink-0">
  <div class="container mt-4">

{%if user.is_authenticated %}
{% include 'partials/_user.html' %}
{% endif %}

  </div>

    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th style="width: 5%" scope="col">#</th>
            <th style="width: 40%" scope="col">Nome</th>
            <th style="width: 35%" scope="col">Email</th>
            {% if user.is_superuser %}
            <th colspan="2" scope="colgroup" class="text-center">Ações</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
         {% if usuarios %}
            {% for item in usuarios %}
          <tr>
            <th scope="row"><p></p></th>
            <td>{{ item.first_name.capitalize.title }} {{item.last_name.capitalize}}</td>
            <td>{{ item.email }}</td>
            {% if user.is_superuser %}
            <td class="text-center" rowspan="1"><a role="button" class="btn btn-green text-white" href="{% url 'editar' item.username %}">Editar</a></button></td>
            <td class="text-center" rowspan="1"><a role="button" class=" btn btn-danger text-white" href="{% url 'deletar_usuario' item.id %}">Excluir</a></button></td>
            {% endif %}
          </tr>
            {% endfor %}
        {% else %}
          <h1>Ainda não há Usuários cadastrados</h1>
        {% endif %}

        </tbody>
      </table>

      {% include 'partials/_pagination_profs.html' %}

    </div>
  </div>
</main>

{% include 'partials/_footer.html' %}

{% endblock %}

templates/usuarios/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'partials/_header.html' %}

<style>

.btn-green{
background-color:#008000
;color: #FFF;
}

.btn-green:hover{
color:#fff;
background-color: #009900;
border-color: #008000;
}

.btn-xl {
    width: 20%;
}

</style>

<main role="main">
    <div class="container">
<!-- ##### Contact Form Area Start ##### -->
        <div class="contact-area section-padding-0-80">
            <div class="container mt-4">
                <div class="row">
                    <div class="col-12">
                        <div class="section-heading">
                            <h2>Login</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="contact-form-area">
                            <form action="{% url 'login' %}" method="POST">
                                <div class="row">
                                    <div class="col-12">
                                        {{ form.email.label }}
                                        {{ form.email }}
                                    </div>
                                    {% for error in form.email.errors %}
                                        <section class="alert alert-danger col-12" role="alert">
                                            {{ form.email.errors }}
                                        </section>
                                    {% endfor %}

                                    <div class="col-12">
                                        {{ form.senha.label }}
                                        {{ form.senha }}
                                    </div>
                                    {% for error in form.senha.errors %}
                                        <section class="alert alert-danger col-12" role="alert">
                                            {{ form.senha.errors }}
                                        </section>
                                    {% endfor %}


                                </div>

                                <div class="d-flex p-2 bd-highlight">
                                    <div class="col-12 text-center">
                                        <button class="btn btn-green btn-xl" type="submit">Acessar sua conta</button>
                                        <a role="button" href="recuperar_senha" class="btn btn-primary btn-xl">Esqueci a senha</a>
                                        {% csrf_token %}
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<script>
function exibirCriarConta()
{
     location.href = "{% url 'cadastro' %}";
}
</script>

{% include 'partials/_footer.html' %}

{% endblock %}

templates/usuarios/recuperar_senha.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'partials/_header.html' %}

<style>

.btn-green{
background-color:#008000
;color: #FFF;
}

.btn-green:hover{
color:#fff;
background-color: #009900;
border-color: #008000;
}

.btn-xl {
    width: 20%;
}

</style>

<main role="main">
    <div class="container">
<!-- ##### Contact Form Area Start ##### -->
        <div class="contact-area section-padding-0-80">
            <div class="container mt-4">
                <div class="row">
                    <div class="col-12">
                        <div class="section-heading">
                            <h2>Recuperar Senha!</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="contact-form-area">
                            <form method="POST">
                                <br>
                                {% csrf_token %}
                                <div class="input-group mb-3">
                                  <input placeholder="Ex: jose@email.com" class="form-control col-12 col-lg-6" type="email" name="email" autocomplete="email" maxlength="254" required="" id="id_email">
                                  <div class="input-group-append">
                                    <button class="btn btn-green" type="submit">Enviar</button>
                                  </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<script>
function exibirCriarConta()
{
     location.href = "{% url 'cadastro' %}";
}
</script>

{% include 'partials/_footer.html' %}

{% endblock %}